feat(logs): add --timestamp and --follow flags
liara-cloud/liara-cli pull request #116
Opened 2023-07-27 14:23 UTC by erfanium

Hello all.
I have added --timestamp and --follow flags to `liara logs` command.  
these two flags will exactly behave like docker's --timestamp` and --follow flags.

Also sometimes fetching logs from server takes more than 1 second, so i added `pendingPooling` to prevent the cli from sending simultaneous request to the server.

2023-07-27 15:18 UTC, mhemrg commented
We should also enable `follow` and `timestamps` by default here:

https://github.com/liara-cloud/liara-cli/blob/75a9f4e0d9b51475568067498fc631125ea93fd4/src/commands/deploy.ts#L187-L197

2023-07-27 21:24 UTC, erfanium commented
@mhemrg done

2023-07-28 07:28 UTC, mhemrg commented
Great job, Erfan.

Changing the default behavior of this command is a breaking change. But we're also aiming for Docker CLI compatibility.
What do you think @guoard?

2023-07-28 11:25 UTC, erfanium commented
Let me explain some real-world use cases of this PR tp show why current liara logs command is not well designed.

1. some apps/frameworks are using json logs. (e.g. fastify, pino). I need to pipe the logs into another json processing tool. (like jq). so I would need an option to see my actual app logs without extra modification: no timestamp, no colorizing. with respect to stdin/stderr.

```sh
liara logs -a=myapp -f | jq
```

2. currently there is no option to disable the follow behavior of liara logs. so it's not easy to save the logs into a file. currently this command will never exit:
```sh
liara logs -a=myapp > app.log
````

2023-07-28 11:41 UTC, erfanium commented
I have another personal suggestion you can think of it.
`colorfulAccessLog` is extra here. this can be a considered as a cute feature but it will silently changed the app log and can introduce problems. also it's not part of docker

2023-07-28 11:58 UTC, mhemrg commented
What if we add another flag to enable colorized output?

2023-07-28 13:15 UTC, guoard approved these changes
@erfanium's explanations of the use cases are both reasonable and well-thought-out and I don't foresee any issues with releasing a new major version.

2023-07-28 14:21 UTC, erfanium commented
new changes:
- I have added --colorize flag
- timestamp are now formatted in isoDateString. to be align be with docker

2023-07-28 17:40 UTC, mhemrg requested changes

2023-07-28 17:40 UTC, mhemrg commented on README.md
> +  -t, --timestamp      Show timestamps
Let's use the plural version: https://docs.docker.com/engine/reference/commandline/logs/#options

```suggestion
  -t, --timestamps      Show timestamps
```

2023-07-28 17:40 UTC, mhemrg commented on src/commands/app/logs.ts
> +    const { follow, colorize, timestamp } = flags;
```suggestion
    const { follow, colorize, timestamps } = flags;
```

2023-07-28 17:40 UTC, mhemrg commented on src/commands/app/logs.ts
> +    timestamp: Flags.boolean({
```suggestion
    timestamps: Flags.boolean({
```

2023-07-28 17:40 UTC, mhemrg commented on src/commands/app/logs.ts
> +    if (this.#timestamp) {
```suggestion
    if (this.#timestamps) {
```

2023-07-28 17:40 UTC, mhemrg commented on src/commands/deploy.ts
> +        '--timestamp',
```suggestion
        '--timestamps',
```

2023-07-28 17:40 UTC, mhemrg commented on src/commands/app/logs.ts
> +    this.#timestamp = timestamp;
```suggestion
    this.#timestamps = timestamps;
```

2023-07-28 17:42 UTC, mhemrg commented
Everything looks good to me @erfanium.
Let's just make the `timestamps` flag compatible with Docker CLI. We can then proceed to merge this.

2023-07-28 17:44 UTC, mhemrg commented
And just a quick note worth mentioning: don't bother updating the readme. Before publishing the new version to npm, it will be generated automatically.

2023-07-28 18:52 UTC, erfanium commented
@mhemrg done

2023-08-09 06:51 UTC, mhemrg requested changes
Hi @erfanium,
I've been using this PR lately and it works fine. Just asked for a few tweaks and then we're good to go ahead and merge this.

2023-08-09 06:51 UTC, mhemrg commented on src/commands/app/logs.ts
> +      description: 'Show timestamps',
To be consistent with the rest of the project, let's use lowercase descriptions:
```suggestion
      description: 'show timestamps',
```

2023-08-09 06:51 UTC, mhemrg commented on src/commands/app/logs.ts
> +      description: 'Follow log output',
```suggestion
      description: 'follow log output',
```

2023-08-09 06:51 UTC, mhemrg commented on src/commands/app/logs.ts
> +      description: 'Colorize log output',
```suggestion
      description: 'colorize log output',
```

2023-08-09 09:21 UTC, merged